#!/bin/bash

set -ex

setup_hugepages() {
    if ! mount | grep -q "^none on /dev/huge type hugetlbfs " ; then
        mkdir -p /dev/huge
        mount -t hugetlbfs none /dev/huge
        echo 1024 > /proc/sys/vm/nr_hugepages
    fi
}

run() {
    # from http://file.brq.redhat.com/~thaller/SDP-CP-agent.docx
    setup_hugepages
    chroot /host modprobe vfio-pci
    echo 0000:06:00.0 > /sys/bus/pci/drivers/mrvl_cn10k_dpi/unbind || :
    echo vfio-pci > /sys/bus/pci/devices/0000:06:00.0/driver_override
    echo vfio-pci > /sys/bus/pci/devices/0001:00:10.0/driver_override
    echo 0000:06:00.0 > /sys/bus/pci/drivers_probe
    echo 0001:00:10.0 > /sys/bus/pci/drivers_probe

    exec /usr/bin/octep_cp_agent /usr/bin/cn106xx.cfg -- --dpi_dev 0000:06:00.0 --pem_dev 0001:00:10.0
}

run
